music/urls.py
from django.conf.urls import url
from . import views
app_name='music'
urlpatterns=[
url(r'^$',views.index,name='index'),
url(r'^(?P<album_id>\d+)/$',views.detail,name='detail'),
url(r'^(?P<album_id>\d+)/favorite/$',views.favorite,name='favorite')
]

website/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/',include('music.urls') ),
]

music/models.py
from django.db import models

class Album(models.Model):
    artist=models.CharField(max_length=50)
    album_title=models.CharField(max_length=500)
    genre=models.CharField(max_length=50)
    album_logo=models.CharField(max_length=1000)
    def __str__(self):
        return self.artist+'---'+self.album_title

class Song(models.Model):
    album=models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type=models.CharField(max_length=20)
    song_title=models.CharField(max_length=50)
    is_favorite=models.BooleanField(default=False)
    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404
from .models import Album,Song

def index(request):
    all_albums=Album.objects.all()
    return render(request,'music/index.html',{'albums':all_albums})


def detail(request,album_id):
    #try:
    #   album=Album.objects.get(pk=album_id)
    #except Album.DoesNotExist:
    #   raise Http404('Album does not exists!!!') 
    album=get_object_or_404(Album,pk=album_id)
    return render(request,'music/detail.html',{'album':album})

def favorite(request,album_id):
    album=get_object_or_404(Album,pk=album_id)
    try:
       sel_song=album.song_set.get(pk=request.POST['song'])
    except (KeyError,Song.DoesNotExist):
       return render(request,'music/detail.html',{'album':album, 'error_message':'Not a valid song'}) 
    else: 
       if sel_song.is_favorite:
          sel_song.is_favorite=False
          sel_song.save()
       else:
          sel_song.is_favorite=True
          sel_song.save()  
       return render(request,'music/detail.html',{'album':album} )

music/templates/music/detail.html
<img src="{{album.album_logo}}">

<h1>{{album.album_title}}</h1>
<h3>{{album.artist}}</h3>
{% if error_message %}
<p><strong>{{error_message}}</strong></p>
{% endif %}
<form action="{% url 'music:favorite' album.id %}" method='POST'> 
{% csrf_token %}
{% for song in album.song_set.all%}
<input type='radio' id='song{{forloop.counter}}' name='song' value='{{song.id}}' > 
<label for='song{{forloop.counter}}'>{{song.song_title}} 
{% if song.is_favorite %}
<img src='' >
{%endif%}</label><br>
{% endfor%}
<input type='submit' value='Submit'>
</form>

music/templates/music/index.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.css">
<link rel='stylesheet' type='text/css' href='{% static 'music/css/style.css' %}'>
<script src="https://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<!-- header -->
<nav class="navbar navbar-inverse">
  <div class='container-fluid'>
     <div class='navbar-header'>
       <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#topNavBar' >
       <span class='icon-bar'></span>
       <span class='icon-bar'></span>
       <span class='icon-bar'></span>
       </button>
       <a href='{% url 'music:index'%}' class='navbar-brand'>MCloud</a>
     </div>
<!-- items -->
     <div class='collapse navbar-collapse'>
      <ul class='nav navbar-nav'>
         <li class=''>
           <a href ='{% url 'music:index'%}'><span class='glyphicon glyphicon-cd' aria-hidden='true'></span>&nbsp Albums</a>
         </li> 
         <li class=''>
           <a href ='#'><span class='glyphicon glyphicon-music' aria-hidden='true'></span>&nbsp Songs</a>
         </li> 
      </ul>
     </div>
  </div>
</nav>

{%if albums %}
<h3>Here are all albums</h3>
<ul>
{% for items in  albums%}
<li><a href="{% url 'music:detail' items.id%}">{{items.album_title}}</a></li>

{% endfor %}
</ul>
{% else %}
    <h3> You do not have any album</h3>
{% endif %}